name: 'Build'

permissions:
  contents: 'read'

on:
  pull_request:
  push:
    branches: [ 'master' ]

jobs:
  build:
    name: 'build, test and publish'
    runs-on: '${{ matrix.os }}'

    strategy:
      matrix:
        os: [ 'ubuntu-latest', 'macos-latest', 'windows-latest' ]

    steps:
      - name: 'Checkout repository'
        uses: 'actions/checkout@v2'


      - name: 'Setup JDK 8'
        uses: 'actions/setup-java@v3'
        with:
          java-version: '8'
          distribution: 'corretto'

      - name: 'Validate gradle wrapper'
        uses: 'gradle/wrapper-validation-action@v1'

      - name: 'Setup Gradle permissions'
        run: 'chmod +x gradlew'


      - name: 'Test project'
        run: './gradlew test'

      - name: 'Build project'
        run: './gradlew build'

      - name: 'Publish project'
        run: './gradlew publishToMavenLocal'
